### ISSUE TITLE
重庆的时间显不出来

### ISSUE THREAD

**Issue by drlovelove** [JohnWong/bus-today#13]
http://api.chelaile.net.cn:7000/bus/stop!stoplist.action?stopName=%E4%BA%94%E9%87%8C%E5%BA%97&s=IOS&v=2.9&cityId=003&sign=

{"arrivalTime":0,

**Comment by JohnWong** [comment]
你可以看看车来了是不是一样时间显示不出来。也可以charles抓包看一下车来了应用的网络请求。

我现在没有时间和动力维护这个项目了。最早的时候主要是车来了界面做得太烂，有一些bug，我才搞了这个项目练练手。后面车来了的api改版过一次，我跟着改了一次。实时距离数据变成了非常不准确的预计到站时间。后面车来了有没有改版不清楚了，因为我现在已经改成使用杭州公交公司的应用，信息比车来了更能准确。

**Comment by drlovelove** [comment]
我也在用你的今日公交APP，那个里面可以显示时间。车来了也可以看到时间但是API call了就显不出来。麻烦你帮我看一下。我的中文不太好。你可以说英语吗？

**Comment by JohnWong** [comment]
Of course, you can write in English.

I have found that, I did not use the api `stop!stoplist.action`. If you want to see the arrival time in a station. You can:

1. Search station using 'http://api.chelaile.net.cn:7000/bus/query!fuzzy.action?sign=&v=5.2.0&s=IOS&sv=9.1&vc=10070&cityId=003&key=%E4%BA%94%E9%87%8C%E5%BA%97`. Find a station id in the result, for example `023-629`.
2. Query arrival time in this station using `http://api.chelaile.net.cn:7000/bus/stop!stationDetail.action?sign=&v=5.2.0&s=IOS&sv=9.1&vc=10070&cityId=003&stationId=023-629`. Then you can find useful information in the result.

**Comment by drlovelove** [comment]
Thanks for your help, Its working well but I am having issue with the arrival time " arrivalTime":1487826185262". How can I convert it to minutes ? Any OFSET time involved ?

**Comment by JohnWong** [comment]
Please check this project, you will get the answer.
https://github.com/JohnWong/bus-today/blob/93329806bbd6a5da3c62ea5bb990fa5f657c9c00/Common/Item/StopLine/JWStopLineItem.m#L33

**Comment by drlovelove** [comment]
Hi, I have read those codes but not sure how we can covert 13 digits unix time to real time . what we did is : parseDate(atol(arrivalTimes[index].c_str())/1000); 
Our goal is to get arrival time/travel time for particular buses for the same bus station. which one should we focus ? arrival time or travel time ?
